version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: subitizing
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  prisma:
    image: prismagraphql/prisma:latest
    environment:
      PRISMA_CONFIG: '{"databases":[{"name":"default","connector":"postgresql","host":"db","port":5432,"user":"your_username","password":"your_password","database":"your_database"}]}'
    depends_on:
      - db
    ports:
      - '4466:4466'

volumes:
  db_data:
